"""Health-report copy, per language (#539).

The charging health report is the one answer surface that had NO language
handling at all: its summary, its curve names and every stop-reason string were
hard-coded Chinese literals, so every reader — including the consumer entry —
got Chinese regardless of `Accept-Language`.

What is translated here is only what WE author:

- the summary sentence and the curve series names;
- the stop-reason text, from two places: the YKC code table (the upstream sends
  a numeric code, we supply the words) and the four fallbacks used when the
  upstream sends nothing.

What is NOT here, deliberately:

- `order.stopped_reason_content` — the upstream's own text. It is DATA describing
  an HTTP-layer reason; translating it would rewrite what the source reported.
  It is passed through verbatim, and this module never sees it.
- The `code` / `status` / `unit` / `reason_code` fields — contract identifiers
  the client renders (standard-api-contract.md §5.4).
"""

from __future__ import annotations

from aiops_diagnostics.i18n import DEFAULT_LANGUAGE

#: The three summary sentences. Keys mirror the branches in
#: ``health_report.build_minimal_health_report``.
HEALTH_SUMMARY_MESSAGES: dict[str, dict[str, str]] = {
    "zh": {
        "normal": "本次充电健康报告包含 1 项正常指标",
        "attention": "本次充电健康报告有 1 项指标需关注",
        "insufficient": "本次充电健康报告有 1 项指标因数据不足无法评估",
    },
    "zh-Hant": {
        "normal": "本次充電健康報告包含 1 項正常指標",
        "attention": "本次充電健康報告有 1 項指標需關注",
        "insufficient": "本次充電健康報告有 1 項指標因資料不足無法評估",
    },
    "en": {
        "normal": "This charging health report contains 1 normal indicator",
        "attention": "This charging health report has 1 indicator that needs attention",
        "insufficient": (
            "This charging health report has 1 indicator that could not be assessed for lack of data"
        ),
    },
    "de": {
        "normal": "Dieser Ladegesundheitsbericht enthält 1 normalen Indikator",
        "attention": "In diesem Ladegesundheitsbericht ist 1 Indikator auffällig",
        "insufficient": (
            "In diesem Ladegesundheitsbericht konnte 1 Indikator mangels Daten nicht bewertet werden"
        ),
    },
    "fr": {
        "normal": "Ce rapport de santé de charge contient 1 indicateur normal",
        "attention": "Ce rapport de santé de charge comporte 1 indicateur à surveiller",
        "insufficient": (
            "Dans ce rapport de santé de charge, 1 indicateur n'a pas pu être évalué faute de données"
        ),
    },
    "es": {
        "normal": "Este informe de salud de carga contiene 1 indicador normal",
        "attention": "Este informe de salud de carga tiene 1 indicador que requiere atención",
        "insufficient": "En este informe de salud de carga, 1 indicador no pudo evaluarse por falta de datos",
    },
    "pt": {
        "normal": "Este relatório de saúde de carregamento contém 1 indicador normal",
        "attention": "Este relatório de saúde de carregamento tem 1 indicador que requer atenção",
        "insufficient": (
            "Neste relatório de saúde de carregamento, 1 indicador não pôde ser avaliado por falta de dados"
        ),
    },
    "vi": {
        "normal": "Báo cáo sức khỏe sạc này có 1 chỉ số bình thường",
        "attention": "Báo cáo sức khỏe sạc này có 1 chỉ số cần lưu ý",
        "insufficient": "Báo cáo sức khỏe sạc này có 1 chỉ số không thể đánh giá do thiếu dữ liệu",
    },
    "mn": {
        "normal": "Энэ цэнэглэлтийн эрүүл мэндийн тайланд 1 хэвийн үзүүлэлт байна",
        "attention": "Энэ цэнэглэлтийн эрүүл мэндийн тайланд анхаарах 1 үзүүлэлт байна",
        "insufficient": (
            "Энэ цэнэглэлтийн эрүүл мэндийн тайланд мэдээлэл хүрэлцэхгүйгээс 1 үзүүлэлтийг үнэлж чадсангүй"
        ),
    },
    "th": {
        "normal": "รายงานสุขภาพการชาร์จนี้มีตัวชี้วัดปกติ 1 รายการ",
        "attention": "รายงานสุขภาพการชาร์จนี้มีตัวชี้วัดที่ต้องเฝ้าระวัง 1 รายการ",
        "insufficient": "รายงานสุขภาพการชาร์จนี้มีตัวชี้วัด 1 รายการที่ประเมินไม่ได้เนื่องจากข้อมูลไม่พอ",
    },
    "km": {
        "normal": "របាយការណ៍សុខភាពសាកថ្មនេះមានសូចនាករធម្មតា 1",
        "attention": "របាយការណ៍សុខភាពសាកថ្មនេះមានសូចនាករ 1 ដែលត្រូវយកចិត្តទុកដាក់",
        "insufficient": "របាយការណ៍សុខភាពសាកថ្មនេះមានសូចនាករ 1 ដែលមិនអាចវាយតម្លៃបានព្រោះខ្វះទិន្នន័យ",
    },
}

#: Curve series display names, keyed by the field name the curve is built from.
HEALTH_CURVE_NAMES: dict[str, dict[str, str]] = {
    "zh": {
        "power": "实际功率",
        "outputCurrent": "输出电流",
        "outputVoltage": "输出电压",
        "temperature": "电池温度",
        "batteryMaxTemperature": "最高温度",
        "batteryMinTemperature": "最低温度",
    },
    "zh-Hant": {
        "power": "實際功率",
        "outputCurrent": "輸出電流",
        "outputVoltage": "輸出電壓",
        "temperature": "電池溫度",
        "batteryMaxTemperature": "最高溫度",
        "batteryMinTemperature": "最低溫度",
    },
    "en": {
        "power": "Actual power",
        "outputCurrent": "Output current",
        "outputVoltage": "Output voltage",
        "temperature": "Battery temperature",
        "batteryMaxTemperature": "Maximum temperature",
        "batteryMinTemperature": "Minimum temperature",
    },
    "de": {
        "power": "Ist-Leistung",
        "outputCurrent": "Ausgangsstrom",
        "outputVoltage": "Ausgangsspannung",
        "temperature": "Batterietemperatur",
        "batteryMaxTemperature": "Höchsttemperatur",
        "batteryMinTemperature": "Mindesttemperatur",
    },
    "fr": {
        "power": "Puissance réelle",
        "outputCurrent": "Courant de sortie",
        "outputVoltage": "Tension de sortie",
        "temperature": "Température de la batterie",
        "batteryMaxTemperature": "Température maximale",
        "batteryMinTemperature": "Température minimale",
    },
    "es": {
        "power": "Potencia real",
        "outputCurrent": "Corriente de salida",
        "outputVoltage": "Tensión de salida",
        "temperature": "Temperatura de la batería",
        "batteryMaxTemperature": "Temperatura máxima",
        "batteryMinTemperature": "Temperatura mínima",
    },
    "pt": {
        "power": "Potência real",
        "outputCurrent": "Corrente de saída",
        "outputVoltage": "Tensão de saída",
        "temperature": "Temperatura da bateria",
        "batteryMaxTemperature": "Temperatura máxima",
        "batteryMinTemperature": "Temperatura mínima",
    },
    "vi": {
        "power": "Công suất thực",
        "outputCurrent": "Dòng ra",
        "outputVoltage": "Điện áp ra",
        "temperature": "Nhiệt độ pin",
        "batteryMaxTemperature": "Nhiệt độ cao nhất",
        "batteryMinTemperature": "Nhiệt độ thấp nhất",
    },
    "mn": {
        "power": "Бодит чадал",
        "outputCurrent": "Гаралтын гүйдэл",
        "outputVoltage": "Гаралтын хүчдэл",
        "temperature": "Батерейны температур",
        "batteryMaxTemperature": "Хамгийн өндөр температур",
        "batteryMinTemperature": "Хамгийн бага температур",
    },
    "th": {
        "power": "กำลังไฟจริง",
        "outputCurrent": "กระแสขาออก",
        "outputVoltage": "แรงดันขาออก",
        "temperature": "อุณหภูมิแบตเตอรี่",
        "batteryMaxTemperature": "อุณหภูมิสูงสุด",
        "batteryMinTemperature": "อุณหภูมิต่ำสุด",
    },
    "km": {
        "power": "ថាមពលជាក់ស្តែង",
        "outputCurrent": "ចរន្តចេញ",
        "outputVoltage": "តង់ស្យុងចេញ",
        "temperature": "សីតុណ្ហភាពថ្ម",
        "batteryMaxTemperature": "សីតុណ្ហភាពខ្ពស់បំផុត",
        "batteryMinTemperature": "សីតុណ្ហភាពទាបបំផុត",
    },
}

#: The four fallbacks used when the upstream supplies no stop-reason text.
HEALTH_STOP_FALLBACK_MESSAGES: dict[str, dict[str, str]] = {
    "zh": {
        "manual_stop": "平台或用户主动停止",
        "package_exhausted": "套餐耗尽",
        "start_failure": "启动失败",
        "unknown_stop_reason": "未提供停止原因",
        "ykc_unknown_code": "YKC 停止码 {code}",
        "reported_stop_reason": "充电桩报告了停止原因",
        "user_or_normal_stop": "用户主动停止或正常充满",
        "communication_or_power_loss": "通信或供电中断",
        "normal_stop": "正常停止",
        "device_or_vehicle_fault": "设备或车辆故障",
        "over_temperature": "过温保护",
        "power_loss": "断电",
        "balance_insufficient": "余额不足",
    },
    "zh-Hant": {
        "manual_stop": "平臺或使用者主動停止",
        "package_exhausted": "套餐耗盡",
        "start_failure": "啟動失敗",
        "unknown_stop_reason": "未提供停止原因",
        "ykc_unknown_code": "YKC 停止碼 {code}",
        "reported_stop_reason": "充電樁報告了停止原因",
        "user_or_normal_stop": "使用者主動停止或正常充滿",
        "communication_or_power_loss": "通訊或供電中斷",
        "normal_stop": "正常停止",
        "device_or_vehicle_fault": "裝置或車輛故障",
        "over_temperature": "過溫保護",
        "power_loss": "斷電",
        "balance_insufficient": "餘額不足",
    },
    "en": {
        "manual_stop": "Stopped by the platform or the user",
        "package_exhausted": "Package exhausted",
        "start_failure": "Start-up failed",
        "unknown_stop_reason": "No stop reason provided",
        "ykc_unknown_code": "YKC stop code {code}",
        "reported_stop_reason": "The charger reported a stop reason",
        "user_or_normal_stop": "Stopped by the user or fully charged",
        "communication_or_power_loss": "Communication or power interrupted",
        "normal_stop": "Stopped normally",
        "device_or_vehicle_fault": "Device or vehicle fault",
        "over_temperature": "Over-temperature protection",
        "power_loss": "Power loss",
        "balance_insufficient": "Insufficient balance",
    },
    "de": {
        "manual_stop": "Von der Plattform oder dem Nutzer beendet",
        "package_exhausted": "Tarifpaket aufgebraucht",
        "start_failure": "Start fehlgeschlagen",
        "unknown_stop_reason": "Kein Stoppgrund angegeben",
        "ykc_unknown_code": "YKC-Stoppcode {code}",
        "reported_stop_reason": "Die Ladestation hat einen Stoppgrund gemeldet",
        "user_or_normal_stop": "Vom Nutzer beendet oder vollständig geladen",
        "communication_or_power_loss": "Kommunikation oder Stromversorgung unterbrochen",
        "normal_stop": "Normal beendet",
        "device_or_vehicle_fault": "Geräte- oder Fahrzeugfehler",
        "over_temperature": "Übertemperaturschutz",
        "power_loss": "Stromausfall",
        "balance_insufficient": "Guthaben nicht ausreichend",
    },
    "fr": {
        "manual_stop": "Arrêt par la plateforme ou l'utilisateur",
        "package_exhausted": "Forfait épuisé",
        "start_failure": "Échec du démarrage",
        "unknown_stop_reason": "Aucun motif d'arrêt fourni",
        "ykc_unknown_code": "Code d'arrêt YKC {code}",
        "reported_stop_reason": "La borne a signalé un motif d'arrêt",
        "user_or_normal_stop": "Arrêt par l'utilisateur ou charge complète",
        "communication_or_power_loss": "Communication ou alimentation interrompue",
        "normal_stop": "Arrêt normal",
        "device_or_vehicle_fault": "Défaillance de la borne ou du véhicule",
        "over_temperature": "Protection contre la surchauffe",
        "power_loss": "Coupure d'alimentation",
        "balance_insufficient": "Solde insuffisant",
    },
    "es": {
        "manual_stop": "Detenido por la plataforma o el usuario",
        "package_exhausted": "Paquete agotado",
        "start_failure": "Fallo de arranque",
        "unknown_stop_reason": "No se indicó el motivo de parada",
        "ykc_unknown_code": "Código de parada YKC {code}",
        "reported_stop_reason": "El cargador informó de un motivo de parada",
        "user_or_normal_stop": "Detenido por el usuario o carga completa",
        "communication_or_power_loss": "Comunicación o alimentación interrumpida",
        "normal_stop": "Parada normal",
        "device_or_vehicle_fault": "Fallo del cargador o del vehículo",
        "over_temperature": "Protección por sobretemperatura",
        "power_loss": "Corte de suministro",
        "balance_insufficient": "Saldo insuficiente",
    },
    "pt": {
        "manual_stop": "Parado pela plataforma ou pelo utilizador",
        "package_exhausted": "Pacote esgotado",
        "start_failure": "Falha no arranque",
        "unknown_stop_reason": "Motivo de paragem não indicado",
        "ykc_unknown_code": "Código de paragem YKC {code}",
        "reported_stop_reason": "O carregador comunicou um motivo de paragem",
        "user_or_normal_stop": "Parado pelo utilizador ou carga completa",
        "communication_or_power_loss": "Comunicação ou alimentação interrompida",
        "normal_stop": "Paragem normal",
        "device_or_vehicle_fault": "Falha do carregador ou do veículo",
        "over_temperature": "Proteção contra sobretemperatura",
        "power_loss": "Corte de energia",
        "balance_insufficient": "Saldo insuficiente",
    },
    "vi": {
        "manual_stop": "Nền tảng hoặc người dùng chủ động dừng",
        "package_exhausted": "Gói đã hết",
        "start_failure": "Khởi động thất bại",
        "unknown_stop_reason": "Không có lý do dừng",
        "ykc_unknown_code": "Mã dừng YKC {code}",
        "reported_stop_reason": "Trụ sạc đã báo lý do dừng",
        "user_or_normal_stop": "Người dùng dừng hoặc sạc đầy",
        "communication_or_power_loss": "Mất kết nối hoặc mất nguồn",
        "normal_stop": "Dừng bình thường",
        "device_or_vehicle_fault": "Lỗi thiết bị hoặc xe",
        "over_temperature": "Bảo vệ quá nhiệt",
        "power_loss": "Mất điện",
        "balance_insufficient": "Số dư không đủ",
    },
    "mn": {
        "manual_stop": "Платформ эсвэл хэрэглэгч зогсоосон",
        "package_exhausted": "Багц дууссан",
        "start_failure": "Эхлүүлэлт амжилтгүй",
        "unknown_stop_reason": "Зогсолтын шалтгаан өгөгдөөгүй",
        "ykc_unknown_code": "YKC зогсолтын код {code}",
        "reported_stop_reason": "Цэнэглэгч зогсолтын шалтгааныг мэдэгдсэн",
        "user_or_normal_stop": "Хэрэглэгч зогсоосон эсвэл бүрэн цэнэглэгдсэн",
        "communication_or_power_loss": "Холбоо эсвэл цахилгаан тасарсан",
        "normal_stop": "Хэвийн зогссон",
        "device_or_vehicle_fault": "Төхөөрөмж эсвэл тээврийн хэрэгслийн гэмтэл",
        "over_temperature": "Хэт халалтаас хамгаалалт",
        "power_loss": "Цахилгаан тасарсан",
        "balance_insufficient": "Үлдэгдэл хүрэлцэхгүй",
    },
    "th": {
        "manual_stop": "แพลตฟอร์มหรือผู้ใช้สั่งหยุดเอง",
        "package_exhausted": "แพ็กเกจหมด",
        "start_failure": "เริ่มทำงานไม่สำเร็จ",
        "unknown_stop_reason": "ไม่มีเหตุผลการหยุด",
        "ykc_unknown_code": "รหัสหยุด YKC {code}",
        "reported_stop_reason": "สถานีชาร์จแจ้งเหตุผลการหยุด",
        "user_or_normal_stop": "ผู้ใช้สั่งหยุดหรือชาร์จเต็ม",
        "communication_or_power_loss": "การสื่อสารหรือไฟฟ้าขัดข้อง",
        "normal_stop": "หยุดตามปกติ",
        "device_or_vehicle_fault": "อุปกรณ์หรือตัวรถขัดข้อง",
        "over_temperature": "ป้องกันอุณหภูมิเกิน",
        "power_loss": "ไฟดับ",
        "balance_insufficient": "ยอดเงินไม่เพียงพอ",
    },
    "km": {
        "manual_stop": "វេទិកា ឬអ្នកប្រើបានបញ្ឈប់ដោយខ្លួនឯង",
        "package_exhausted": "កញ្ចប់អស់ហើយ",
        "start_failure": "ការចាប់ផ្តើមបរាជ័យ",
        "unknown_stop_reason": "មិនបានផ្តល់មូលហេតុបញ្ឈប់",
        "ykc_unknown_code": "កូដបញ្ឈប់ YKC {code}",
        "reported_stop_reason": "ស្ថានីយ៍សាកបានរាយការណ៍ពីមូលហេតុបញ្ឈប់",
        "user_or_normal_stop": "អ្នកប្រើបញ្ឈប់ ឬសាកពេញ",
        "communication_or_power_loss": "ការទំនាក់ទំនង ឬអគ្គិសនីដាច់",
        "normal_stop": "បញ្ឈប់ធម្មតា",
        "device_or_vehicle_fault": "ឧបករណ៍ ឬយានយន្តខូច",
        "over_temperature": "ការពារកំដៅលើស",
        "power_loss": "អគ្គិសនីដាច់",
        "balance_insufficient": "សមតុល្យមិនគ្រប់គ្រាន់",
    },
}

#: The YKC stop-code table, per language, keyed by numeric code as a string.
#:
#: These are OUR words describing the upstream's codes — the upstream sends only
#: the number — so they are ours to translate. 33 codes × 6 languages.
YKC_STOP_REASON_MESSAGES: dict[str, dict[str, str]] = {
    "zh": {
        "64": "APP 远程停止",
        "65": "SOC 达到 100%",
        "66": "充电电量满足设定条件",
        "67": "充电金额满足设定条件",
        "68": "充电时间满足设定条件",
        "69": "手动停止充电",
        "70": "车端正常主动停止",
        "74": "启动失败：充电桩控制系统故障",
        "75": "启动失败：控制导引断开",
        "76": "启动失败：断路器跳位",
        "77": "启动失败：电表通信中断",
        "78": "启动失败：余额不足",
        "79": "启动失败：充电模块故障",
        "80": "启动失败：急停开入",
        "83": "启动失败：温度异常",
        "85": "启动失败：电子锁异常",
        "87": "启动失败：绝缘异常",
        "88": "启动失败：枪故障",
        "106": "异常中止：系统闭锁",
        "107": "异常中止：导引断开",
        "108": "异常中止：断路器跳位",
        "109": "异常中止：电表通信中断",
        "110": "异常中止：余额不足",
        "113": "异常中止：充电模块故障",
        "114": "异常中止：急停开入",
        "116": "异常中止：温度异常",
        "119": "异常中止：电子锁异常",
        "124": "异常中止：电池组过温",
        "131": "异常中止：充电桩断电",
        "138": "异常中止：设备故障",
        "141": "异常中止：枪故障",
        "142": "异常中止：充电数据异常",
        "144": "未知原因停止",
    },
    "zh-Hant": {
        "64": "APP 遠端停止",
        "65": "SOC 達到 100%",
        "66": "充電電量滿足設定條件",
        "67": "充電金額滿足設定條件",
        "68": "充電時間滿足設定條件",
        "69": "手動停止充電",
        "70": "車端正常主動停止",
        "74": "啟動失敗：充電樁控制系統故障",
        "75": "啟動失敗：控制導引斷開",
        "76": "啟動失敗：斷路器跳位",
        "77": "啟動失敗：電錶通訊中斷",
        "78": "啟動失敗：餘額不足",
        "79": "啟動失敗：充電模組故障",
        "80": "啟動失敗：急停開入",
        "83": "啟動失敗：溫度異常",
        "85": "啟動失敗：電子鎖異常",
        "87": "啟動失敗：絕緣異常",
        "88": "啟動失敗：槍故障",
        "106": "異常中止：系統閉鎖",
        "107": "異常中止：導引斷開",
        "108": "異常中止：斷路器跳位",
        "109": "異常中止：電錶通訊中斷",
        "110": "異常中止：餘額不足",
        "113": "異常中止：充電模組故障",
        "114": "異常中止：急停開入",
        "116": "異常中止：溫度異常",
        "119": "異常中止：電子鎖異常",
        "124": "異常中止：電池組過溫",
        "131": "異常中止：充電樁斷電",
        "138": "異常中止：裝置故障",
        "141": "異常中止：槍故障",
        "142": "異常中止：充電資料異常",
        "144": "未知原因停止",
    },
    "en": {
        "64": "Stopped remotely from the app",
        "65": "SOC reached 100%",
        "66": "Charged energy reached the configured limit",
        "67": "Charged amount reached the configured limit",
        "68": "Charging time reached the configured limit",
        "69": "Charging stopped manually",
        "70": "Stopped normally by the vehicle",
        "74": "Start-up failed: charger control system fault",
        "75": "Start-up failed: control pilot disconnected",
        "76": "Start-up failed: circuit breaker tripped",
        "77": "Start-up failed: meter communication lost",
        "78": "Start-up failed: insufficient balance",
        "79": "Start-up failed: charging module fault",
        "80": "Start-up failed: emergency stop engaged",
        "83": "Start-up failed: abnormal temperature",
        "85": "Start-up failed: electronic lock fault",
        "87": "Start-up failed: insulation fault",
        "88": "Start-up failed: connector fault",
        "106": "Aborted: system interlock",
        "107": "Aborted: pilot disconnected",
        "108": "Aborted: circuit breaker tripped",
        "109": "Aborted: meter communication lost",
        "110": "Aborted: insufficient balance",
        "113": "Aborted: charging module fault",
        "114": "Aborted: emergency stop engaged",
        "116": "Aborted: abnormal temperature",
        "119": "Aborted: electronic lock fault",
        "124": "Aborted: battery pack overtemperature",
        "131": "Aborted: charger power lost",
        "138": "Aborted: equipment fault",
        "141": "Aborted: connector fault",
        "142": "Aborted: abnormal charging data",
        "144": "Stopped for an unknown reason",
    },
    "de": {
        "64": "Aus der App heraus ferngestoppt",
        "65": "SOC hat 100 % erreicht",
        "66": "Geladene Energiemenge hat den eingestellten Wert erreicht",
        "67": "Ladebetrag hat den eingestellten Wert erreicht",
        "68": "Ladezeit hat den eingestellten Wert erreicht",
        "69": "Laden manuell beendet",
        "70": "Vom Fahrzeug normal beendet",
        "74": "Start fehlgeschlagen: Störung der Ladesteuerung",
        "75": "Start fehlgeschlagen: Steuerpilot getrennt",
        "76": "Start fehlgeschlagen: Schutzschalter ausgelöst",
        "77": "Start fehlgeschlagen: Zählerkommunikation unterbrochen",
        "78": "Start fehlgeschlagen: Guthaben nicht ausreichend",
        "79": "Start fehlgeschlagen: Störung des Lademoduls",
        "80": "Start fehlgeschlagen: Not-Aus ausgelöst",
        "83": "Start fehlgeschlagen: Temperatur auffällig",
        "85": "Start fehlgeschlagen: Störung der elektronischen Verriegelung",
        "87": "Start fehlgeschlagen: Isolationsfehler",
        "88": "Start fehlgeschlagen: Störung des Ladesteckers",
        "106": "Abgebrochen: Systemverriegelung",
        "107": "Abgebrochen: Steuerpilot getrennt",
        "108": "Abgebrochen: Schutzschalter ausgelöst",
        "109": "Abgebrochen: Zählerkommunikation unterbrochen",
        "110": "Abgebrochen: Guthaben nicht ausreichend",
        "113": "Abgebrochen: Störung des Lademoduls",
        "114": "Abgebrochen: Not-Aus ausgelöst",
        "116": "Abgebrochen: Temperatur auffällig",
        "119": "Abgebrochen: Störung der elektronischen Verriegelung",
        "124": "Abgebrochen: Überhitzung des Batteriepakets",
        "131": "Abgebrochen: Stromausfall an der Ladestation",
        "138": "Abgebrochen: Gerätestörung",
        "141": "Abgebrochen: Störung des Ladesteckers",
        "142": "Abgebrochen: Ladedaten auffällig",
        "144": "Aus unbekanntem Grund beendet",
    },
    "fr": {
        "64": "Arrêt à distance depuis l'application",
        "65": "SOC atteint 100 %",
        "66": "L'énergie chargée a atteint la limite configurée",
        "67": "Le montant chargé a atteint la limite configurée",
        "68": "La durée de charge a atteint la limite configurée",
        "69": "Charge arrêtée manuellement",
        "70": "Arrêt normal par le véhicule",
        "74": "Échec du démarrage : défaut du système de contrôle de la borne",
        "75": "Échec du démarrage : pilote de contrôle déconnecté",
        "76": "Échec du démarrage : disjoncteur déclenché",
        "77": "Échec du démarrage : communication du compteur perdue",
        "78": "Échec du démarrage : solde insuffisant",
        "79": "Échec du démarrage : défaut du module de charge",
        "80": "Échec du démarrage : arrêt d'urgence enclenché",
        "83": "Échec du démarrage : température anormale",
        "85": "Échec du démarrage : défaut du verrou électronique",
        "87": "Échec du démarrage : défaut d'isolement",
        "88": "Échec du démarrage : défaut du connecteur",
        "106": "Interrompu : verrouillage du système",
        "107": "Interrompu : pilote déconnecté",
        "108": "Interrompu : disjoncteur déclenché",
        "109": "Interrompu : communication du compteur perdue",
        "110": "Interrompu : solde insuffisant",
        "113": "Interrompu : défaut du module de charge",
        "114": "Interrompu : arrêt d'urgence enclenché",
        "116": "Interrompu : température anormale",
        "119": "Interrompu : défaut du verrou électronique",
        "124": "Interrompu : surchauffe du pack de batteries",
        "131": "Interrompu : coupure d'alimentation de la borne",
        "138": "Interrompu : défaut de l'équipement",
        "141": "Interrompu : défaut du connecteur",
        "142": "Interrompu : données de charge anormales",
        "144": "Arrêt pour une raison inconnue",
    },
    "es": {
        "64": "Detenido de forma remota desde la aplicación",
        "65": "SOC alcanzó el 100 %",
        "66": "La energía cargada alcanzó el límite configurado",
        "67": "El importe cargado alcanzó el límite configurado",
        "68": "El tiempo de carga alcanzó el límite configurado",
        "69": "Carga detenida manualmente",
        "70": "Detenido con normalidad por el vehículo",
        "74": "Fallo de arranque: avería del sistema de control del cargador",
        "75": "Fallo de arranque: piloto de control desconectado",
        "76": "Fallo de arranque: interruptor automático disparado",
        "77": "Fallo de arranque: comunicación del contador perdida",
        "78": "Fallo de arranque: saldo insuficiente",
        "79": "Fallo de arranque: avería del módulo de carga",
        "80": "Fallo de arranque: parada de emergencia activada",
        "83": "Fallo de arranque: temperatura anómala",
        "85": "Fallo de arranque: avería del cierre electrónico",
        "87": "Fallo de arranque: fallo de aislamiento",
        "88": "Fallo de arranque: avería del conector",
        "106": "Interrumpido: bloqueo del sistema",
        "107": "Interrumpido: piloto desconectado",
        "108": "Interrumpido: interruptor automático disparado",
        "109": "Interrumpido: comunicación del contador perdida",
        "110": "Interrumpido: saldo insuficiente",
        "113": "Interrumpido: avería del módulo de carga",
        "114": "Interrumpido: parada de emergencia activada",
        "116": "Interrumpido: temperatura anómala",
        "119": "Interrumpido: avería del cierre electrónico",
        "124": "Interrumpido: sobretemperatura del paquete de baterías",
        "131": "Interrumpido: corte de alimentación del cargador",
        "138": "Interrumpido: avería del equipo",
        "141": "Interrumpido: avería del conector",
        "142": "Interrumpido: datos de carga anómalos",
        "144": "Detenido por una razón desconocida",
    },
    "pt": {
        "64": "Parado remotamente a partir da aplicação",
        "65": "SOC atingiu 100 %",
        "66": "A energia carregada atingiu o limite configurado",
        "67": "O montante carregado atingiu o limite configurado",
        "68": "O tempo de carregamento atingiu o limite configurado",
        "69": "Carregamento parado manualmente",
        "70": "Parado normalmente pelo veículo",
        "74": "Falha no arranque: avaria do sistema de controlo do carregador",
        "75": "Falha no arranque: piloto de controlo desligado",
        "76": "Falha no arranque: disjuntor disparado",
        "77": "Falha no arranque: comunicação do contador perdida",
        "78": "Falha no arranque: saldo insuficiente",
        "79": "Falha no arranque: avaria do módulo de carregamento",
        "80": "Falha no arranque: paragem de emergência acionada",
        "83": "Falha no arranque: temperatura anómala",
        "85": "Falha no arranque: avaria do fecho eletrónico",
        "87": "Falha no arranque: falha de isolamento",
        "88": "Falha no arranque: avaria do conector",
        "106": "Interrompido: bloqueio do sistema",
        "107": "Interrompido: piloto desligado",
        "108": "Interrompido: disjuntor disparado",
        "109": "Interrompido: comunicação do contador perdida",
        "110": "Interrompido: saldo insuficiente",
        "113": "Interrompido: avaria do módulo de carregamento",
        "114": "Interrompido: paragem de emergência acionada",
        "116": "Interrompido: temperatura anómala",
        "119": "Interrompido: avaria do fecho eletrónico",
        "124": "Interrompido: sobretemperatura do conjunto de baterias",
        "131": "Interrompido: corte de energia no carregador",
        "138": "Interrompido: avaria do equipamento",
        "141": "Interrompido: avaria do conector",
        "142": "Interrompido: dados de carregamento anómalos",
        "144": "Parado por motivo desconhecido",
    },
    "vi": {
        "64": "Dừng từ xa qua ứng dụng",
        "65": "SOC đạt 100%",
        "66": "Điện lượng sạc đạt điều kiện cài đặt",
        "67": "Số tiền sạc đạt điều kiện cài đặt",
        "68": "Thời gian sạc đạt điều kiện cài đặt",
        "69": "Dừng sạc thủ công",
        "70": "Xe chủ động dừng bình thường",
        "74": "Khởi động thất bại: lỗi hệ thống điều khiển trụ sạc",
        "75": "Khởi động thất bại: ngắt tín hiệu điều khiển",
        "76": "Khởi động thất bại: aptomat nhảy",
        "77": "Khởi động thất bại: mất liên lạc công tơ",
        "78": "Khởi động thất bại: số dư không đủ",
        "79": "Khởi động thất bại: lỗi mô-đun sạc",
        "80": "Khởi động thất bại: dừng khẩn cấp",
        "83": "Khởi động thất bại: nhiệt độ bất thường",
        "85": "Khởi động thất bại: lỗi khóa điện tử",
        "87": "Khởi động thất bại: lỗi cách điện",
        "88": "Khởi động thất bại: lỗi súng sạc",
        "106": "Dừng bất thường: khóa hệ thống",
        "107": "Dừng bất thường: ngắt tín hiệu dẫn hướng",
        "108": "Dừng bất thường: aptomat nhảy",
        "109": "Dừng bất thường: mất liên lạc công tơ",
        "110": "Dừng bất thường: số dư không đủ",
        "113": "Dừng bất thường: lỗi mô-đun sạc",
        "114": "Dừng bất thường: dừng khẩn cấp",
        "116": "Dừng bất thường: nhiệt độ bất thường",
        "119": "Dừng bất thường: lỗi khóa điện tử",
        "124": "Dừng bất thường: pin quá nhiệt",
        "131": "Dừng bất thường: trụ sạc mất điện",
        "138": "Dừng bất thường: lỗi thiết bị",
        "141": "Dừng bất thường: lỗi súng sạc",
        "142": "Dừng bất thường: dữ liệu sạc bất thường",
        "144": "Dừng do nguyên nhân không rõ",
    },
    "mn": {
        "64": "Аппаас алсаас зогсоосон",
        "65": "SOC 100% хүрсэн",
        "66": "Цэнэглэсэн эрчим хүч тохиргоонд хүрсэн",
        "67": "Цэнэглэсэн дүн тохиргоонд хүрсэн",
        "68": "Цэнэглэх хугацаа тохиргоонд хүрсэн",
        "69": "Цэнэглэлтийг гараар зогсоосон",
        "70": "Тээврийн хэрэгсэл хэвийн зогсоосон",
        "74": "Эхлүүлэлт амжилтгүй: цэнэглэгчийн удирдлагын системийн алдаа",
        "75": "Эхлүүлэлт амжилтгүй: удирдлагын дохио тасарсан",
        "76": "Эхлүүлэлт амжилтгүй: автомат унтраалга ажилласан",
        "77": "Эхлүүлэлт амжилтгүй: тоолуурын холбоо тасарсан",
        "78": "Эхлүүлэлт амжилтгүй: үлдэгдэл хүрэлцэхгүй",
        "79": "Эхлүүлэлт амжилтгүй: цэнэглэх модулийн алдаа",
        "80": "Эхлүүлэлт амжилтгүй: яаралтай зогсолт",
        "83": "Эхлүүлэлт амжилтгүй: температур хэвийн бус",
        "85": "Эхлүүлэлт амжилтгүй: цахилгаан түгжээний алдаа",
        "87": "Эхлүүлэлт амжилтгүй: тусгаарлалтын алдаа",
        "88": "Эхлүүлэлт амжилтгүй: цэнэглэгч бууны алдаа",
        "106": "Хэвийн бус зогсолт: систем түгжигдсэн",
        "107": "Хэвийн бус зогсолт: удирдлагын дохио тасарсан",
        "108": "Хэвийн бус зогсолт: автомат унтраалга ажилласан",
        "109": "Хэвийн бус зогсолт: тоолуурын холбоо тасарсан",
        "110": "Хэвийн бус зогсолт: үлдэгдэл хүрэлцэхгүй",
        "113": "Хэвийн бус зогсолт: цэнэглэх модулийн алдаа",
        "114": "Хэвийн бус зогсолт: яаралтай зогсолт",
        "116": "Хэвийн бус зогсолт: температур хэвийн бус",
        "119": "Хэвийн бус зогсолт: цахилгаан түгжээний алдаа",
        "124": "Хэвийн бус зогсолт: батерей хэт халсан",
        "131": "Хэвийн бус зогсолт: цэнэглэгч цахилгаангүй болсон",
        "138": "Хэвийн бус зогсолт: төхөөрөмжийн алдаа",
        "141": "Хэвийн бус зогсолт: цэнэглэгч бууны алдаа",
        "142": "Хэвийн бус зогсолт: цэнэглэлтийн өгөгдөл хэвийн бус",
        "144": "Тодорхойгүй шалтгаанаар зогссон",
    },
    "th": {
        "64": "หยุดจากระยะไกลผ่านแอป",
        "65": "SOC ถึง 100%",
        "66": "ปริมาณไฟที่ชาร์จถึงเงื่อนไขที่ตั้งไว้",
        "67": "จำนวนเงินที่ชาร์จถึงเงื่อนไขที่ตั้งไว้",
        "68": "เวลาชาร์จถึงเงื่อนไขที่ตั้งไว้",
        "69": "หยุดชาร์จด้วยตนเอง",
        "70": "รถหยุดเองตามปกติ",
        "74": "เริ่มทำงานไม่สำเร็จ: ระบบควบคุมตู้ชาร์จขัดข้อง",
        "75": "เริ่มทำงานไม่สำเร็จ: สัญญาณควบคุมขาด",
        "76": "เริ่มทำงานไม่สำเร็จ: เบรกเกอร์ตัด",
        "77": "เริ่มทำงานไม่สำเร็จ: การสื่อสารมิเตอร์ขาด",
        "78": "เริ่มทำงานไม่สำเร็จ: ยอดเงินไม่พอ",
        "79": "เริ่มทำงานไม่สำเร็จ: โมดูลชาร์จขัดข้อง",
        "80": "เริ่มทำงานไม่สำเร็จ: ปุ่มหยุดฉุกเฉินทำงาน",
        "83": "เริ่มทำงานไม่สำเร็จ: อุณหภูมิผิดปกติ",
        "85": "เริ่มทำงานไม่สำเร็จ: กลอนไฟฟ้าขัดข้อง",
        "87": "เริ่มทำงานไม่สำเร็จ: ฉนวนผิดปกติ",
        "88": "เริ่มทำงานไม่สำเร็จ: หัวชาร์จขัดข้อง",
        "106": "หยุดผิดปกติ: ระบบล็อก",
        "107": "หยุดผิดปกติ: สัญญาณนำขาด",
        "108": "หยุดผิดปกติ: เบรกเกอร์ตัด",
        "109": "หยุดผิดปกติ: การสื่อสารมิเตอร์ขาด",
        "110": "หยุดผิดปกติ: ยอดเงินไม่พอ",
        "113": "หยุดผิดปกติ: โมดูลชาร์จขัดข้อง",
        "114": "หยุดผิดปกติ: ปุ่มหยุดฉุกเฉินทำงาน",
        "116": "หยุดผิดปกติ: อุณหภูมิผิดปกติ",
        "119": "หยุดผิดปกติ: กลอนไฟฟ้าขัดข้อง",
        "124": "หยุดผิดปกติ: แบตเตอรี่ร้อนเกิน",
        "131": "หยุดผิดปกติ: ตู้ชาร์จไฟดับ",
        "138": "หยุดผิดปกติ: อุปกรณ์ขัดข้อง",
        "141": "หยุดผิดปกติ: หัวชาร์จขัดข้อง",
        "142": "หยุดผิดปกติ: ข้อมูลการชาร์จผิดปกติ",
        "144": "หยุดด้วยสาเหตุที่ไม่ทราบ",
    },
    "km": {
        "64": "បញ្ឈប់ពីចម្ងាយតាមកម្មវិធី",
        "65": "SOC ដល់ 100%",
        "66": "បរិមាណថាមពលសាកដល់លក្ខខណ្ឌកំណត់",
        "67": "ចំនួនទឹកប្រាក់សាកដល់លក្ខខណ្ឌកំណត់",
        "68": "ពេលវេលាសាកដល់លក្ខខណ្ឌកំណត់",
        "69": "បញ្ឈប់ការសាកដោយដៃ",
        "70": "រថយន្តបញ្ឈប់ដោយខ្លួនឯងធម្មតា",
        "74": "ការចាប់ផ្តើមបរាជ័យ៖ បញ្ហាប្រព័ន្ធគ្រប់គ្រងស្ថានីយសាក",
        "75": "ការចាប់ផ្តើមបរាជ័យ៖ សញ្ញាគ្រប់គ្រងដាច់",
        "76": "ការចាប់ផ្តើមបរាជ័យ៖ ឧបករណ៍កាត់ចរន្តដំណើរការ",
        "77": "ការចាប់ផ្តើមបរាជ័យ៖ ការទំនាក់ទំនងម៉ែត្រដាច់",
        "78": "ការចាប់ផ្តើមបរាជ័យ៖ សមតុល្យមិនគ្រប់គ្រាន់",
        "79": "ការចាប់ផ្តើមបរាជ័យ៖ បញ្ហាម៉ូឌុលសាក",
        "80": "ការចាប់ផ្តើមបរាជ័យ៖ ប៊ូតុងបញ្ឈប់បន្ទាន់ដំណើរការ",
        "83": "ការចាប់ផ្តើមបរាជ័យ៖ សីតុណ្ហភាពមិនប្រក្រតី",
        "85": "ការចាប់ផ្តើមបរាជ័យ៖ បញ្ហាសោអេឡិចត្រូនិក",
        "87": "ការចាប់ផ្តើមបរាជ័យ៖ បញ្ហាអ៊ីសូឡង់",
        "88": "ការចាប់ផ្តើមបរាជ័យ៖ បញ្ហាក្បាលសាក",
        "106": "បញ្ឈប់មិនប្រក្រតី៖ ប្រព័ន្ធចាក់សោ",
        "107": "បញ្ឈប់មិនប្រក្រតី៖ សញ្ញានាំដាច់",
        "108": "បញ្ឈប់មិនប្រក្រតី៖ ឧបករណ៍កាត់ចរន្តដំណើរការ",
        "109": "បញ្ឈប់មិនប្រក្រតី៖ ការទំនាក់ទំនងម៉ែត្រដាច់",
        "110": "បញ្ឈប់មិនប្រក្រតី៖ សមតុល្យមិនគ្រប់គ្រាន់",
        "113": "បញ្ឈប់មិនប្រក្រតី៖ បញ្ហាម៉ូឌុលសាក",
        "114": "បញ្ឈប់មិនប្រក្រតី៖ ប៊ូតុងបញ្ឈប់បន្ទាន់ដំណើរការ",
        "116": "បញ្ឈប់មិនប្រក្រតី៖ សីតុណ្ហភាពមិនប្រក្រតី",
        "119": "បញ្ឈប់មិនប្រក្រតី៖ បញ្ហាសោអេឡិចត្រូនិក",
        "124": "បញ្ឈប់មិនប្រក្រតី៖ ថ្មក្តៅខ្លាំង",
        "131": "បញ្ឈប់មិនប្រក្រតី៖ ស្ថានីយសាកដាច់ចរន្ត",
        "138": "បញ្ឈប់មិនប្រក្រតី៖ បញ្ហាឧបករណ៍",
        "141": "បញ្ឈប់មិនប្រក្រតី៖ បញ្ហាក្បាលសាក",
        "142": "បញ្ឈប់មិនប្រក្រតី៖ ទិន្នន័យសាកមិនប្រក្រតី",
        "144": "បញ្ឈប់ដោយមូលហេតុមិនស្គាល់",
    },
}


def _pack(table: dict[str, dict[str, str]], language: str) -> dict[str, str]:
    return table.get(language) or table[DEFAULT_LANGUAGE]


def health_summary(language: str, key: str) -> str:
    """The report's summary sentence for one status branch."""
    pack = _pack(HEALTH_SUMMARY_MESSAGES, language)
    return pack.get(key) or HEALTH_SUMMARY_MESSAGES[DEFAULT_LANGUAGE]["insufficient"]


def curve_name(language: str, field: str) -> str:
    """A curve series display name. An unknown field falls back to the field
    name itself rather than an empty label — a chart legend must say something."""
    return _pack(HEALTH_CURVE_NAMES, language).get(field) or field


def stop_reason_fallback(language: str, classification: str) -> str | None:
    """The fallback text for a classification, or ``None`` when the
    classification has none (most of them do not: the upstream's own text
    usually carries the reason, and we only supply words for the four cases
    where it does not)."""
    pack = _pack(HEALTH_STOP_FALLBACK_MESSAGES, language)
    return pack.get(classification) or HEALTH_STOP_FALLBACK_MESSAGES[DEFAULT_LANGUAGE].get(classification)


def ykc_stop_reason(language: str, code: int, fallback: str) -> str:
    """The description of a YKC stop code. ``fallback`` is the caller's own
    text (upstream content, or the synthesised code label) and is used when the
    code is not in the table — it is never translated."""
    pack = _pack(YKC_STOP_REASON_MESSAGES, language)
    return pack.get(str(code)) or _pack(YKC_STOP_REASON_MESSAGES, DEFAULT_LANGUAGE).get(str(code)) or fallback
